// Common types used across the application

export type Language = 'en' | 'hi' | 'pa'

export type TranslationKeys = {
  common: {
    loading: string
    error: string
    success: string
    cancel: string
    save: string
    edit: string
    delete: string
    back: string
    next: string
    submit: string
    close: string
    yes: string
    no: string
    ok: string
    search: string
    filter: string
    clear: string
    refresh: string
    retry: string
    continue: string
    skip: string
    done: string
    select: string
    required: string
    optional: string
    name: string
    email: string
    phone: string
    age: string
    gender: string
    address: string
    male: string
    female: string
    other: string
    currentLocation: string
    openMenu: string
    tapToOpen: string
  }
  nav: {
    home: string
    consultation: string
    symptoms: string
    records: string
    medicines: string
    profile: string
    login: string
    signup: string
    logout: string
  }
  auth: {
    loginTitle: string
    loginSubtitle: string
    username: string
    password: string
    loginButton: string
    createAccount: string
    demoCredentials: string
    signupTitle: string
    signupSubtitle: string
    confirmPassword: string
    signupButton: string
    alreadyHaveAccount: string
    signInHere: string
    forgotPassword: string
    resetPassword: string
  }
  signup: {
    step1: {
      title: string
      subtitle: string
      usernameLabel: string
      usernamePlaceholder: string
      emailLabel: string
      emailPlaceholder: string
      passwordLabel: string
      passwordPlaceholder: string
      confirmPasswordLabel: string
      confirmPasswordPlaceholder: string
      nextButton: string
      alreadyHaveAccount: string
      signInHere: string
    }
    step2: {
      title: string
      subtitle: string
      nameLabel: string
      namePlaceholder: string
      phoneLabel: string
      phonePlaceholder: string
      genderLabel: string
      ageLabel: string
      agePlaceholder: string
      addressLabel: string
      addressPlaceholder: string
      addEquipmentButton: string
      skipButton: string
      backButton: string
    }
    step3: {
      title: string
      subtitle: string
      selectedEquipment: string
      createAccountButton: string
      backButton: string
    }
  }
  home: {
    welcome: string
    subtitle: string
    quickActions: string
    recentConsultations: string
    noConsultations: string
    startConsultation: string
    viewRecords: string
    checkSymptoms: string
    emergency: string
  }
  consultation: {
    title: string
    subtitle: string
    describeSymptoms: string
    symptomsPlaceholder: string
    addImage: string
    voiceInput: string
    analyzeButton: string
    followUpQuestion: string
    followUpPlaceholder: string
    submitFollowUp: string
    skipFollowUp: string
    analyzing: string
    reportTitle: string
    likelyCondition: string
    urgency: string
    recommendedAction: string
    instantRemedies: string
    followUps: string
    summaryForDoctor: string
    disclaimers: string
    highUrgency: string
    mediumUrgency: string
    lowUrgency: string
  }
  records: {
    title: string
    subtitle: string
    addRecord: string
    addPatient: string
    noRecords: string
    noPatients: string
    patientName: string
    visitDate: string
    diagnosis: string
    treatment: string
    notes: string
    doctorName: string
    symptoms: string
    triageHistory: string
    medicalRecords: string
    patients: string
  }
  profile: {
    title: string
    subtitle: string
    personalInfo: string
    equipment: string
    settings: string
    language: string
    notifications: string
    privacy: string
    about: string
    version: string
    support: string
    terms: string
    privacyPolicy: string
  }
  equipment: {
    title: string
    subtitle: string
    addEquipment: string
    removeEquipment: string
    noEquipment: string
    availableEquipment: string
    myEquipment: string
    thermometer: string
    bloodPressureMonitor: string
    pulseOximeter: string
    glucoseMeter: string
    weightScale: string
    stethoscope: string
    firstAidKit: string
    oxygenConcentrator: string
    nebulizer: string
    ecgMachine: string
    defibrillator: string
    wheelchair: string
    walkingCane: string
    crutches: string
    other: string
  }
  errors: {
    networkError: string
    serverError: string
    validationError: string
    authenticationError: string
    permissionError: string
    notFound: string
    genericError: string
    usernameExists: string
    invalidCredentials: string
    passwordMismatch: string
    requiredField: string
    invalidEmail: string
    passwordTooShort: string
    voiceNotSupported: string
  }
  success: {
    accountCreated: string
    profileUpdated: string
    recordAdded: string
    recordUpdated: string
    recordDeleted: string
    equipmentAdded: string
    equipmentRemoved: string
    consultationSaved: string
  }
  time: {
    now: string
    today: string
    yesterday: string
    thisWeek: string
    thisMonth: string
    thisYear: string
    ago: string
    in: string
    minutes: string
    hours: string
    days: string
    weeks: string
    months: string
    years: string
  }
}
